### ISSUE TITLE
can you make the mod to support RAGENativeUI.dll v1.6.3？It's not compatible UltimateBackup menu left and right navigation.

### ISSUE THREAD

**Issue by kklzz1982** [craftycram/MechanicBackupPlugin#1]
can you make the mod to support RAGENativeUI.dll v1.6.3？It's not compatible UltimateBackup menu left and right navigation.

thanks！

**Comment by craftycram** [comment]
It should all work together if you installed the newest version of all three plugins.
UltimateBackup: 1.8.3.2
MechnicBackup: 1.1.0.0
RageNativeUI: 1.7.0.0
So just update your RageNative (newest version is included in my download)

**Comment by craftycram** [comment]
I'm closing this issue now. If you have any further issues feel free to open it back up again.

**Comment by craftycram** [comment]
I'm closing this issue now. If you have any further issues feel free to open it back up again.

**Comment by Michael21107** [comment]
@craftycram Since no fixes have been made, shouldn't this issue be closed as _not planned_?

**Comment by craftycram** [comment]
closing as planned wasnt an option in 2020…

**Comment by Michael21107** [comment]
I did not know that.
